#!/bin/sh

set -e

bundle exec jekyll build
bundle exec htmlproofer ./_site --disable-external --check-html --check-sri --empty-alt-ignore
bundle exec script/check-site-quality
gem build jekyll-theme-minimal.gemspec
